-- Projects Table
create table if not exists projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  demo_url text,
  repo_url text,
  tags text[] default '{}'::text[]
);

-- Skills Table
create table if not exists skills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text not null, -- 'Frontend', 'Backend', 'Tools'
  level integer default 0
);

-- Experience Table
create table if not exists experiences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  role text not null,
  company text not null,
  period text not null,
  description text,
  type text default 'work' -- 'work' or 'education'
);

-- Certificates Table
create table if not exists certificates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  issuer text not null,
  date date,
  credential_url text,
  image_url text
);

-- Messages Table (Contact Form)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  read boolean default false
);

-- Enable RLS
alter table projects enable row level security;
alter table skills enable row level security;
alter table experiences enable row level security;
alter table certificates enable row level security;
alter table messages enable row level security;

-- RLS Policies (Drop existing then create to avoid errors)

-- Projects Policies
drop policy if exists "Public projects are viewable by everyone." on projects;
create policy "Public projects are viewable by everyone." on projects for select using (true);

drop policy if exists "Users can insert their own projects." on projects;
create policy "Users can insert their own projects." on projects for insert with check (auth.role() = 'authenticated');

drop policy if exists "Users can update their own projects." on projects;
create policy "Users can update their own projects." on projects for update using (auth.role() = 'authenticated');

drop policy if exists "Users can delete their own projects." on projects;
create policy "Users can delete their own projects." on projects for delete using (auth.role() = 'authenticated');

-- Skills Policies
drop policy if exists "Public skills are viewable by everyone." on skills;
create policy "Public skills are viewable by everyone." on skills for select using (true);

drop policy if exists "Users can insert skills." on skills;
create policy "Users can insert skills." on skills for insert with check (auth.role() = 'authenticated');

drop policy if exists "Users can update skills." on skills;
create policy "Users can update skills." on skills for update using (auth.role() = 'authenticated');

drop policy if exists "Users can delete skills." on skills;
create policy "Users can delete skills." on skills for delete using (auth.role() = 'authenticated');

-- Experience Policies
drop policy if exists "Public experiences are viewable by everyone." on experiences;
create policy "Public experiences are viewable by everyone." on experiences for select using (true);

drop policy if exists "Users can insert experiences." on experiences;
create policy "Users can insert experiences." on experiences for insert with check (auth.role() = 'authenticated');

drop policy if exists "Users can update experiences." on experiences;
create policy "Users can update experiences." on experiences for update using (auth.role() = 'authenticated');

drop policy if exists "Users can delete experiences." on experiences;
create policy "Users can delete experiences." on experiences for delete using (auth.role() = 'authenticated');

-- Certificates Policies
drop policy if exists "Public certificates are viewable by everyone." on certificates;
create policy "Public certificates are viewable by everyone." on certificates for select using (true);

drop policy if exists "Users can insert certificates." on certificates;
create policy "Users can insert certificates." on certificates for insert with check (auth.role() = 'authenticated');

drop policy if exists "Users can update certificates." on certificates;
create policy "Users can update certificates." on certificates for update using (auth.role() = 'authenticated');

drop policy if exists "Users can delete certificates." on certificates;
create policy "Users can delete certificates." on certificates for delete using (auth.role() = 'authenticated');

-- Messages Policies
drop policy if exists "Anyone can insert messages." on messages;
create policy "Anyone can insert messages." on messages for insert with check (true);

drop policy if exists "Admin can view messages." on messages;
create policy "Admin can view messages." on messages for select using (auth.role() = 'authenticated');

-- Storage Bucket for Images
insert into storage.buckets (id, name, public) values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

drop policy if exists "Images are publicly accessible." on storage.objects;
create policy "Images are publicly accessible." on storage.objects for select using ( bucket_id = 'portfolio' );

drop policy if exists "Admin can upload images." on storage.objects;
create policy "Admin can upload images." on storage.objects for insert with check ( bucket_id = 'portfolio' and auth.role() = 'authenticated' );
